# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datos.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 373)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lb_matricula = QtWidgets.QLabel(self.centralwidget)
        self.lb_matricula.setObjectName("lb_matricula")
        self.gridLayout.addWidget(self.lb_matricula, 0, 0, 1, 1)
        self.le_matricula = QtWidgets.QLineEdit(self.centralwidget)
        self.le_matricula.setObjectName("le_matricula")
        self.gridLayout.addWidget(self.le_matricula, 0, 1, 1, 1)
        self.lb_inicio = QtWidgets.QLabel(self.centralwidget)
        self.lb_inicio.setObjectName("lb_inicio")
        self.gridLayout.addWidget(self.lb_inicio, 1, 0, 1, 1)
        self.le_inicio = QtWidgets.QLineEdit(self.centralwidget)
        self.le_inicio.setObjectName("le_inicio")
        self.gridLayout.addWidget(self.le_inicio, 1, 1, 1, 1)
        self.lb_final = QtWidgets.QLabel(self.centralwidget)
        self.lb_final.setObjectName("lb_final")
        self.gridLayout.addWidget(self.lb_final, 2, 0, 1, 1)
        self.le_final = QtWidgets.QLineEdit(self.centralwidget)
        self.le_final.setObjectName("le_final")
        self.gridLayout.addWidget(self.le_final, 2, 1, 1, 1)
        self.lb_valor_pagar = QtWidgets.QLabel(self.centralwidget)
        self.lb_valor_pagar.setObjectName("lb_valor_pagar")
        self.gridLayout.addWidget(self.lb_valor_pagar, 3, 0, 1, 1)
        self.le_valor_pagar = QtWidgets.QLineEdit(self.centralwidget)
        self.le_valor_pagar.setObjectName("le_valor_pagar")
        self.gridLayout.addWidget(self.le_valor_pagar, 3, 1, 1, 1)
        self.lb_consumo_activa = QtWidgets.QLabel(self.centralwidget)
        self.lb_consumo_activa.setObjectName("lb_consumo_activa")
        self.gridLayout.addWidget(self.lb_consumo_activa, 4, 0, 1, 1)
        self.le_consumo_activa = QtWidgets.QLineEdit(self.centralwidget)
        self.le_consumo_activa.setObjectName("le_consumo_activa")
        self.gridLayout.addWidget(self.le_consumo_activa, 4, 1, 1, 1)
        self.lb_consumo_reactiva = QtWidgets.QLabel(self.centralwidget)
        self.lb_consumo_reactiva.setObjectName("lb_consumo_reactiva")
        self.gridLayout.addWidget(self.lb_consumo_reactiva, 5, 0, 1, 1)
        self.le_consumo_reactiva = QtWidgets.QLineEdit(self.centralwidget)
        self.le_consumo_reactiva.setObjectName("le_consumo_reactiva")
        self.gridLayout.addWidget(self.le_consumo_reactiva, 5, 1, 1, 1)
        self.lb_kw = QtWidgets.QLabel(self.centralwidget)
        self.lb_kw.setObjectName("lb_kw")
        self.gridLayout.addWidget(self.lb_kw, 6, 0, 1, 1)
        self.le_kw = QtWidgets.QLineEdit(self.centralwidget)
        self.le_kw.setObjectName("le_kw")
        self.gridLayout.addWidget(self.le_kw, 6, 1, 1, 1)
        self.lb_valor_kw = QtWidgets.QLabel(self.centralwidget)
        self.lb_valor_kw.setObjectName("lb_valor_kw")
        self.gridLayout.addWidget(self.lb_valor_kw, 7, 0, 1, 1)
        self.le_valor_kw = QtWidgets.QLineEdit(self.centralwidget)
        self.le_valor_kw.setObjectName("le_valor_kw")
        self.gridLayout.addWidget(self.le_valor_kw, 7, 1, 1, 1)
        self.lb_contribucion = QtWidgets.QLabel(self.centralwidget)
        self.lb_contribucion.setObjectName("lb_contribucion")
        self.gridLayout.addWidget(self.lb_contribucion, 8, 0, 1, 1)
        self.le_contribucion = QtWidgets.QLineEdit(self.centralwidget)
        self.le_contribucion.setObjectName("le_contribucion")
        self.gridLayout.addWidget(self.le_contribucion, 8, 1, 1, 1)
        self.lb_alumbrado = QtWidgets.QLabel(self.centralwidget)
        self.lb_alumbrado.setObjectName("lb_alumbrado")
        self.gridLayout.addWidget(self.lb_alumbrado, 9, 0, 1, 1)
        self.le_alumbrado = QtWidgets.QLineEdit(self.centralwidget)
        self.le_alumbrado.setObjectName("le_alumbrado")
        self.gridLayout.addWidget(self.le_alumbrado, 9, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Datos"))
        self.lb_matricula.setText(_translate("MainWindow", "Matricula"))
        self.lb_inicio.setText(_translate("MainWindow", "Fecha Inicio"))
        self.lb_final.setText(_translate("MainWindow", "Fecha Final"))
        self.lb_valor_pagar.setText(_translate("MainWindow", "Valor a Pagar"))
        self.lb_consumo_activa.setText(_translate("MainWindow", "Consumo Activa"))
        self.lb_consumo_reactiva.setText(_translate("MainWindow", "Consumo Reactiva"))
        self.lb_kw.setText(_translate("MainWindow", "Kw/h"))
        self.lb_valor_kw.setText(_translate("MainWindow", "Valor Kw"))
        self.lb_contribucion.setText(_translate("MainWindow", "Contribucion"))
        self.lb_alumbrado.setText(_translate("MainWindow", "Alumbrado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
