#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Nov 11, 2020 04:19:16 PM EST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 201x381+504+131
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Datos"
    vTcl:DefineAlias "$top" "editar" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 455 -width 225 
    vTcl:DefineAlias "$top.fra45" "contenedor" vTcl:WidgetProc "editar" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab46 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Matricula 
    vTcl:DefineAlias "$site_3_0.lab46" "lb_matricula" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab47 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Fechas 
    vTcl:DefineAlias "$site_3_0.lab47" "lb_fechas" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab48 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Valor a pagar} 
    vTcl:DefineAlias "$site_3_0.lab48" "lb_vr_paga" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab49 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Kw/h 
    vTcl:DefineAlias "$site_3_0.lab49" "lb_kw" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab50 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Valor kw/h} 
    vTcl:DefineAlias "$site_3_0.lab50" "lb_vr_kw" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab51 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Alumbrado 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab52 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Consumo activa} 
    vTcl:DefineAlias "$site_3_0.lab52" "lb_consumo_activa" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab53 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Consumo reactiva} 
    vTcl:DefineAlias "$site_3_0.lab53" "lb_consumo_reactiva" vTcl:WidgetProc "editar" 1
    label $site_3_0.lab54 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -justify right -text Contribución 
    vTcl:DefineAlias "$site_3_0.lab54" "lb_contribucion" vTcl:WidgetProc "editar" 1
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Enviar 
    vTcl:DefineAlias "$site_3_0.but55" "btn_enviar" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent56" "entry_matricula" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent57" "entry_fechas" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent58" "entry_vr_pagar" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent59 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent59" "entry_kw" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent60 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent60" "entry_vr_kw" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent61 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent61" "entry_alumbrado" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent62" "entry_consumo_activa" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent63" "entry_consumo_reactiva" vTcl:WidgetProc "editar" 1
    entry $site_3_0.ent64 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent64" "entry_contribucion" vTcl:WidgetProc "editar" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -y 0 -rely 0.026 -width 0 -relwidth 0.498 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -y 0 -rely 0.105 -width 0 -relwidth 0.199 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -y 0 -rely 0.184 -width 0 -relwidth 0.498 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -y 0 -rely 0.263 -width 0 -relwidth 0.498 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -y 0 -rely 0.342 -width 0 -relwidth 0.498 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -y 0 -rely 0.421 -width 0 -relwidth 0.498 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -y 0 -rely 0.5 -width 0 -relwidth 0.498 -height 0 \
        -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -y 0 -rely 0.579 -width 0 -relwidth 0.498 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -y 0 -rely 0.658 -width 0 -relwidth 0.498 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 0 -relx 0.249 -y 0 -rely 0.789 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.026 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 0 -relx 0.204 -y 0 -rely 0.105 -width 158 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.184 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.263 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.342 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.421 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.5 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.579 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 0 -relx 0.502 -y 0 -rely 0.658 -width 98 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.997 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

